### ISSUE TITLE
Unable to read environment values

### ISSUE THREAD

**Issue by mlkwy** [Taehyun-Koh/TeamKeep#6]
[https://stackoverflow.com/questions/72706541/can-you-use-dotenv-in-electron-production](url)
[https://github.com/electron-userland/electron-builder/issues/7143](url)
electron을 dotenv와 사용하는 게 불가능한 것으로 보임

**Comment by Taehyun-Koh** [comment]
I got it figured out. In case someone else is looking for the answer to this question, here is how I got it working.

Step 1: Create a file by the name electron-builder.env at the root level where your package.json resides. Please make sure that you keep the file name as electron-builder.env

Step 2: Define the variables that you would like to inside the electron-builder.env file, for example ELECTRON_BUILD_VERSION=99.99

Step 3: Inside your builder-config.yaml file, access the environment variable with the syntax {env.ELECTRON_BUILD_VERSION}

There you go. Have fun. Happy Coding 😊

**Comment by mlkwy** [comment]
resolved with commit b77cd2e4945187b292cc82320a451d199f38d079 where option to set own sql server configs
